# Generated by Django 5.0.2 on 2025-06-02 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'parameters',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civility', models.CharField(blank=True, max_length=20, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('volume_propose', models.DecimalField(decimal_places=2, max_digits=10)),
                ('biens', models.TextField(help_text='Liste des biens à transporter (texte libre)')),
                ('periode_souhaitee_start', models.DateField()),
                ('periode_souhaitee_end', models.DateField()),
                ('flexibilite', models.BooleanField(default=False)),
                ('adresse_chargement', models.CharField(max_length=255)),
                ('etage_chargement', models.IntegerField()),
                ('passage_chargement', models.CharField(choices=[('ASC', 'Ascenseur'), ('ESC', 'Escalier')], max_length=3)),
                ('adresse_livraison', models.CharField(max_length=255)),
                ('etage_livraison', models.IntegerField()),
                ('passage_livraison', models.CharField(choices=[('ASC', 'Ascenseur'), ('ESC', 'Escalier')], max_length=3)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('REFUSEE', 'Refusée'), ('CLOTUREE', 'Clôturée')], default='EN_COURS', max_length=10)),
                ('code_confidentiel', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'proposition',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RetourVide',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_camion', models.CharField(choices=[('VL', 'VL'), ('PL', 'PL')], max_length=2)),
                ('avec_hayon', models.BooleanField()),
                ('depart_date_start', models.DateField()),
                ('depart_date_end', models.DateField(blank=True, null=True)),
                ('arrival_date_start', models.DateField()),
                ('arrival_date_end', models.DateField(blank=True, null=True)),
                ('detour_possible', models.BooleanField()),
                ('origin', models.CharField(blank=True, max_length=2, null=True)),
                ('destination', models.CharField(blank=True, max_length=2, null=True)),
                ('itineraire', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'retour_vide',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('updateDate', models.DateTimeField(auto_now=True)),
                ('date', models.TextField(blank=True, null=True)),
                ('depart', models.TextField()),
                ('destination', models.TextField()),
                ('volume', models.FloatField()),
                ('price', models.FloatField()),
                ('user_id', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField()),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('civility', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('raison_sociale', models.CharField(blank=True, max_length=255, null=True)),
                ('siret', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('date_inscription', models.DateField(blank=True, db_column='dateInscription', null=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('type_user', models.IntegerField(blank=True, null=True)),
                ('statut_user', models.IntegerField(blank=True, null=True)),
                ('password', models.CharField(max_length=255)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('enabled', models.BooleanField(blank=True, null=True)),
                ('emailVerified', models.BooleanField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id_offre', models.AutoField(db_column='id_offre', primary_key=True, serialize=False)),
                ('destination_date_start', models.DateField(blank=True, db_column='destinationDateStart', null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, db_column='creationDate')),
                ('depart_date_start', models.DateField(blank=True, db_column='departDateStart', null=True)),
                ('destination', models.CharField(blank=True, max_length=255, null=True)),
                ('origin', models.CharField(blank=True, max_length=255, null=True)),
                ('route', models.TextField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, db_column='updateDate', null=True)),
                ('depart_date_end', models.DateField(blank=True, db_column='departDateEnd', null=True)),
                ('destination_date_end', models.DateField(blank=True, db_column='destinationDateEnd', null=True)),
                ('prix', models.IntegerField()),
                ('volume', models.IntegerField()),
                ('reference', models.TextField(blank=True, null=True)),
                ('ascenseur_depart', models.BooleanField(blank=True, db_column='ascenseur_depart', null=True)),
                ('ascenseur_arrivee', models.BooleanField(blank=True, db_column='ascenseur_arrivee', null=True)),
                ('monte_meuble_depart', models.BooleanField(blank=True, db_column='monte_meuble_depart', null=True)),
                ('monte_meuble_arrivee', models.BooleanField(blank=True, db_column='monte_meuble_arrivee', null=True)),
                ('escalier_depart', models.BooleanField(blank=True, db_column='escalier_depart', null=True)),
                ('escalier_arrivee', models.BooleanField(blank=True, db_column='escalier_arrivee', null=True)),
                ('direct_depart', models.BooleanField(blank=True, db_column='direct_depart', null=True)),
                ('direct_arrivee', models.BooleanField(blank=True, db_column='direct_arrivee', null=True)),
                ('depart_etage', models.TextField(blank=True, db_column='depart_etage', null=True)),
                ('arrivee_etage', models.TextField(blank=True, db_column='arrivee_etage', null=True)),
                ('depart_pres', models.TextField(blank=True, db_column='depart_pres', null=True)),
                ('arrivee_pres', models.TextField(blank=True, db_column='arrivee_pres', null=True)),
                ('commentaire', models.TextField(blank=True, db_column='commentaire', null=True)),
                ('type_offre', models.ForeignKey(blank=True, db_column='type_offre', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offres', to='api.parameter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='api.user')),
            ],
            options={
                'db_table': 'offres',
            },
        ),
    ]
