# Generated by Django 5.0.2 on 2025-02-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='id_offre',
            field=models.AutoField(db_column='id_offre', primary_key=True, serialize=False),
        ),
    ]
