# Generated by Django 5.0.2 on 2024-03-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
