# Generated by Django 5.0.2 on 2025-02-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_offre_id_offre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='depart_date_end',
            field=models.DateField(blank=True, db_column='departDateEnd', null=True),
        ),
        migrations.AlterField(
            model_name='offre',
            name='depart_date_start',
            field=models.DateField(blank=True, db_column='departDateStart', null=True),
        ),
        migrations.AlterField(
            model_name='offre',
            name='destination_date_end',
            field=models.DateField(db_column='destinationDateEnd'),
        ),
        migrations.AlterField(
            model_name='offre',
            name='destination_date_start',
            field=models.DateField(blank=True, db_column='destinationDateStart', null=True),
        ),
        migrations.AlterModelTable(
            name='offre',
            table='offres',
        ),
    ]
