# Generated by Django 5.0.2 on 2024-04-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='file',
            field=models.TextField(blank=True, null=True),
        ),
    ]
