# Generated by Django 5.0.2 on 2025-02-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_offre_depart_date_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, db_column='creationDate'),
        ),
        migrations.AlterField(
            model_name='offre',
            name='update_date',
            field=models.DateField(blank=True, db_column='updateDate', null=True),
        ),
    ]
