# Generated by Django 5.0.2 on 2025-02-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_offre_creation_date_alter_offre_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_inscription',
            field=models.DateField(blank=True, db_column='dateInscription', null=True),
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
