# Generated by Django 5.0.2 on 2024-04-17 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
