# Generated by Django 5.0.2 on 2024-04-18 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.TextField(blank=True),
        ),
    ]
