# Generated by Django 5.0.2 on 2025-02-17 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_user_date_inscription_alter_user_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offre',
            name='title',
        ),
    ]
