# Generated by Django 5.0.2 on 2024-04-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='demandes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='offres',
            field=models.TextField(blank=True),
        ),
    ]
