# Generated by Django 5.0.2 on 2025-02-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_offre_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='destination_date_end',
            field=models.DateField(blank=True, db_column='destinationDateEnd', null=True),
        ),
        migrations.AlterField(
            model_name='offre',
            name='update_date',
            field=models.DateTimeField(blank=True, db_column='updateDate', null=True),
        ),
    ]
