# Generated by Django 5.0.2 on 2024-04-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_demandes_user_offres'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='user_id',
            field=models.TextField(default='vide'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offre',
            name='arrival_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offre',
            name='depart_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offre',
            name='itinerary',
            field=models.TextField(default='vide'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offre',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offre',
            name='user_id',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offre',
            name='volume',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
