# Generated by Django 5.0.2 on 2024-04-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_demande_user_id_offre_arrival_date_offre_depart_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='demandes',
        ),
        migrations.RemoveField(
            model_name='user',
            name='offres',
        ),
        migrations.AddField(
            model_name='user',
            name='hideEmail',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='offre',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
