# Generated by Django 5.0.2 on 2024-04-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_user_demandes_remove_user_offres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='depart',
            field=models.TextField(default='vide'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demande',
            name='destination',
            field=models.TextField(default='vide'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demande',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demande',
            name='volume',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
