# Generated by Django 5.0.2 on 2024-05-31 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offre',
            name='itinerary',
        ),
        migrations.RemoveField(
            model_name='offre',
            name='price',
        ),
        migrations.RemoveField(
            model_name='offre',
            name='volume',
        ),
        migrations.AddField(
            model_name='offre',
            name='destination',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offre',
            name='origin',
            field=models.TextField(blank=True, null=True),
        ),
    ]
