# Generated by Django 5.0.2 on 2024-06-01 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_offre_itinerary_remove_offre_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='destinationMap',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offre',
            name='originMap',
            field=models.TextField(blank=True, null=True),
        ),
    ]
