# Generated by Django 5.0.2 on 2024-06-02 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_offre_destinationmap_offre_originmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='route',
            field=models.TextField(blank=True, null=True),
        ),
    ]
