# Generated by Django 5.0.2 on 2024-06-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_offre_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offre',
            name='depart_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
