# Generated by Django 5.0.2 on 2024-06-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_offre_arrival_date_alter_offre_depart_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offre',
            name='arrival_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offre',
            name='depart_date',
            field=models.TextField(blank=True, null=True),
        ),
    ]
