"""
Django settings for marketplace project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ku*hf!uua5+i99m7w()f&kwgsdpm0cm#yt&5*0&-nb%t+^xv(g'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_HEADERS = [
    "content-type",
    "X-CSRFToken",
    "X-Requested-With",
    "accept",
    "origin",
    "authorization",
]
CORS_ALLOW_CREDENTIALS = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api',
    'rest_framework',
    'corsheaders',
    'chat'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'marketplace.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'marketplace.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'demelo',  # Change this to your MySQL database name
        'USER': 'root',  # Change this to your MySQL username
        'PASSWORD': 'demelo',  # Change this to your MySQL password
        'HOST': '127.0.0.1',  # Change if MySQL is running on another server
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb4',  # Supports emojis and special characters
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

import firebase_admin
from firebase_admin import credentials

cred = credentials.Certificate("marketplace/marketplace.json")
firebase_admin.initialize_app(cred)


CORS_ALLOWED_ORIGINS = [
    'http://localhost:4200',
    'http://frontend.a6dwddddhnhpdkgx.eastus.azurecontainer.io',
    'https://ttqdwdn2-4200.euw.devtunnels.ms',

      # Add the origin of your Angular application
    # Add other allowed origins as needed
]
CORS_ORIGIN_WHITELIST = ['https://localhost:4200/admin/companies',    'https://localhost:4200/login/','https://ttqdwdn2-4200.euw.devtunnels.ms/'
 ]

PAYPAL_CLIENT_ID ='ARNVx6a5qIuRIhDkzuo2Uv7SnwOjsrX45p6HxwRV5Hh-JYmuP95loM1XXT8snKhcN4p9E-qdc87W0IS8'
PAYPAL_CLIENT_SECRET='EDyy_2annU1GcqZtfr6PJRG6WgHy1ObQLL-IoLqKFDlfvesbql-Q2IAe0JXxxE0fiispr0XcBYLKsrhV'

SESSION_ENGINE = "django.contrib.sessions.backends.db"  # Stores sessions in DB
SESSION_COOKIE_AGE = 86400  # 1-day session expiry
SESSION_SAVE_EVERY_REQUEST = True  # Updates expiry on each request
SESSION_COOKIE_SAMESITE = 'None'
SESSION_COOKIE_SECURE = False 


import environ

env = environ.Env()
environ.Env.read_env()  # Load environment variables from .env file

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = env("EMAIL_HOST")
EMAIL_PORT = env.int("EMAIL_PORT")
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS")
EMAIL_HOST_USER = env("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER